[tool.poetry]
name = "triflow"
version = "0.5.2"
description = "Automatic finite difference discretization for 1D PDE with fast temporal solvers."

license = "MIT"

authors = [
    "Nicolas Cellier <contact@nicolas-cellier.net>"
]

readme = 'README.md'  # Markdown files are supported

repository = "http://github.com/locie/triflow"
documentation = "https://locie.github.io/triflow"

keywords = ['PDE', 'finite-difference', 'physic',
            'modelling', 'interactive']

[tool.poetry.dependencies]
python = ">=3.5"  # Compatible python versions must be declared here

# core computation
numpy = "^1"
scipy = "^1"
sympy = "^1"
theano = "^1"

# plugins: displays and containers
streamz = "^0.3"
xarray = "^0.10"
holoviews = "^1.1"
bokeh = "^0.12"

# misc: simul name generation and path management
"path.py" = "^11.0"
pendulum = "^1.5"
dask = "^0.17.2"
tqdm = "^4.23"

[tool.poetry.dev-dependencies]
jupyter = "^1.0"
pylama = "^7.4"
pytest = "^3.5"
isort = "^4.3"
matplotlib = "^2.2"
cycler = "^0.10.0"
kiwisolver = "^1.0"
recommonmark = "^0.4.0"
sphinx = "^1.7"
"sphinxcontrib.napoleon" = "^0.6.1"
nbsphinx = "^0.3.3"
nbconvert = "^5.3"
sphinx_rtd_theme = "^0.3.0"
doc8 = "^0.8.0"
scikit-image = "^0.13.1"
python-coveralls = "^2.9"
pytest-cov = "^2.5"

